### ISSUE TITLE
Design principle of plotpy

### ISSUE THREAD

**Issue by wangjiawen2013** [cpmech/plotpy#67]
Hi,
I want to add some scientific plots such as boxplot, violin plot, probality density plot and so on. So I wanna know more about the design principle of plotpy.
There are a lot of parameters in matplotlib, it's hard to include all these parameters in plotpy, though many parameters are rarely used. I notice that there is a parameter called `extra` in barplot.rs:
```
pub struct Barplot {
    label: String,             // Name of this bar in the legend
    colors: Vec<String>,       // Colors for each bar
    width: f64,                // Width of the bars
    bottom: Vec<f64>,          // bottom coordinates to stack bars
    with_text: Option<String>, // Text to be added to each bar (aka, bar_label)
    horizontal: bool,          // Horizontal barplot
    x_errors: Vec<f64>,        // Shows x-error icons on horizontal bars
    extra: String,             // Extra commands (comma separated)
    buffer: String,            // buffer
}
```
So we can set any parameters used in matplotlib barplot using `extra`. But not all structs in plotpy have `extra`. So could you tell about the parameter setting strategy and design principle of plotpy ? Then we can add plotting functions in consistent with your style as possible as we can.

**Comment by cpmech** [comment]
Hi, thanks again for your interest in Plotpy.

The basic "design principle" of Plotpy is being more verbose than Matplotlib. Also, we aim to have multiple functions to set the parameters of a graph instead of having a function with various parameters, as in Matplotlib. That's why we have things such as:

```
set_line_alpha
set_line_color
set_line_style
set_...
```

Instead of:

```
set(alpha, color, line_style, ...)
```

There are a few reasons for this:

1. We never know how many parameters the user wants to use, and forcing the user to pass all parameters would be tedious.
2. We may need more parameters in the future, and Rust doesn't implement "function overloading" (thankfully)
3. Having multiple functions makes our lives easier when using an IDE with intelligent sense, such as VS Code; we type ".", and a list of options appears.
3. It seems easier to document every single function (and Cargo/Rust does a fantastic job)

The main "feature" of Plotpy is the `GraphMaker` trait, which is implemented by things such as `Curve`, `Contour`, and `Text`. The `Plot` structure can then generate the Python script. The `Plot` structure also has many functions to configure the plot.

Concerning the `set_extra` function, I initially added it because I didn't know what people wanted, and I don't use `Barplot` very much. Thus, `set_extra` was left as a "failsafe" for future needs. However, the aim is to have the functionality covered by specific `set_...` functions.

Nonetheless, I have just implemented the `set_extra` function for most structures in version **1.7.0**. The idea is to improve Plotpy as the need arises. Currently, my own simulation needs are pretty much covered, but helping others is good, too.
